In [12]:
import pandas as pd
print('Libraries are Imported')

Libraries are Imported

# INTRO TO DATA FRAMES

In [13]:
nba=pd.read_csv("nba.csv")
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0
...,...,...,...,...,...,...,...,...,...
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,6-5,206.0,Notre Dame,625093.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,6-10,240.0,North Carolina,6980802.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,6-9,215.0,St. John's,2894059.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,6-5,215.0,Duke,6000000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,7-1,245.0,Illinois,3075880.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,6-3,195.0,Weber State,4236287.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,6-4,200.0,Lehigh,2525160.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,6-7,185.0,Westchester CC,525093.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,6-11,235.0,Duke,1415520.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,6-1,173.0,Dayton,2854940.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,6-9,240.0,Indiana,2637720.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
445,Dante Exum,Utah Jazz,11.0,PG,20.0,6-6,190.0,NaN,3777720.0
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,6-10,265.0,Georgia Tech,12000000.0
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,7-1,245.0,NaN,1175880.0
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,6-8,226.0,Butler,15409570.0
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,6-8,226.0,NaN,2050000.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# FUNCTIONS IN THE DATA FRAMES
( THE BELOW MENTIONED SOME OF COMMANDS HOLD FOR ONLY DATA FRAMES AND SOME OTHER HOLD FOR SERIES TOO..)

In [ ]:
print(nba.head(12).count())
nba.tail(12)
print(nba.dtypes)   # brand new seires of dtypes

In [19]:
college=pd.read_csv("nba.csv",usecols= ["College"],squeeze=True)
salary=pd.read_csv("nba.csv" ,usecols= ["Salary"],squeeze=True)
print(college.count())
print('the maximum are', max(salary)+max(college.index))
print(len(college)+len(salary))

373
the maximum are 25000457.0
916

In [ ]:
nba.shape  # ROWS AND COLUMNS

In [ ]:
nba.size

In [ ]:
nba.index

In [ ]:
  nba.columns    # only data frames

In [ ]:
nba.axes    # only data frames

In [ ]:
nba.values

In [15]:
nba.info() # only data frames

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 458 entries, 0 to 457
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     373 non-null object
Salary      446 non-null float64
dtypes: float64(4), object(5)
memory usage: 32.3+ KB

In [14]:
nba.get_dtype_counts()   
# counts number of datatypes and the datatype types as series. d type gives over all list value datatype

float64    4
object     5
dtype: int64

# DIFFERENCE BETWEEN SHARED METHODS

In [5]:
rev= pd.read_csv("revenue.csv",index_col="Date")
rev

FileNotFoundError: File b'revenue.csv' does not exist

In [6]:
s=pd.Series([1,2,3])
s.sum()

6

In [7]:
rev.sum(axis=1)  # axis performs the operation according to the row wise on corresponding row
rev.sum(axis= "columns")

NameError: name 'rev' is not defined

# SELECT ONE COLUMN FROM A DATAFRAME

In [8]:
nba=pd.read_csv("nba.csv")
nba.head(3)

FileNotFoundError: File b'nba.csv' does not exist

In [148]:
# METHOD ONE
nba.Name   # returns as a SERIES  as value=Name
nba.Number # returns as a SERIES  as value=Number
nba.Salary ## returns as a SERIES as value=Salary
output=None  ## Dosen't workout for the columns with spaces.

In [149]:
#METHOD TWO
nba["Name"]     # returns as a SERIES  as value=Name
nba["Number"]   # returns as a SERIES  as value=Number
nba["Salary"]   ## returns as a SERIES as value=Salary

0       7730337.0
1       6796117.0
2             NaN
3       1148640.0
4       5000000.0
5      12000000.0
6       1170960.0
7       2165160.0
8       1824360.0
9       3431040.0
10      2569260.0
11      6912869.0
12      3425510.0
13      1749840.0
14      2616975.0
15      3425510.0
16       845059.0
17      1500000.0
18      1335480.0
19      6300000.0
20      1599840.0
21       134215.0
22      1500000.0
23     19689000.0
24      1140240.0
25       947276.0
26       981348.0
27       947276.0
28       947276.0
29     11235955.0
          ...
428     8042895.0
429      625093.0
430      947276.0
431     6980802.0
432     2894059.0
433     6000000.0
434     5016000.0
435     3075880.0
436     4236287.0
437     2525160.0
438      525093.0
439     1415520.0
440     2854940.0
441     2637720.0
442     4775000.0
443     2658240.0
444     9463484.0
445     3777720.0
446    12000000.0
447     1175880.0
448    15409570.0
449     1348440.0
450     2050000.0
451      981348.0
452     2239800.0
453     2433333.0
454      900000.0
455     2900000.0
456      947276.0
457           NaN
Name: Salary, Length: 458, dtype: float64

In [103]:
nba["Name"] .head()
nba["Number"].head()
nba["Salary"].head(25)

0      7730337.0
1      6796117.0
2            NaN
3      1148640.0
4      5000000.0
5     12000000.0
6      1170960.0
7      2165160.0
8      1824360.0
9      3431040.0
10     2569260.0
11     6912869.0
12     3425510.0
13     1749840.0
14     2616975.0
15     3425510.0
16      845059.0
17     1500000.0
18     1335480.0
19     6300000.0
20     1599840.0
21      134215.0
22     1500000.0
23    19689000.0
24     1140240.0
Name: Salary, dtype: float64

# SELECT Two OR more COLUMN FROM A DATAFRAME

In [150]:
nba[["Team","Name","Number"]]   # here we are givving the columns as the LIST,tis returns a dataframe
nba[["Team","Name","Number"]] .head(25)

              Team                     Name  Number
0   Boston Celtics            Avery Bradley     0.0
1   Boston Celtics              Jae Crowder    99.0
2   Boston Celtics             John Holland    30.0
3   Boston Celtics              R.J. Hunter    28.0
4   Boston Celtics            Jonas Jerebko     8.0
5   Boston Celtics             Amir Johnson    90.0
6   Boston Celtics            Jordan Mickey    55.0
7   Boston Celtics             Kelly Olynyk    41.0
8   Boston Celtics             Terry Rozier    12.0
9   Boston Celtics             Marcus Smart    36.0
10  Boston Celtics          Jared Sullinger     7.0
11  Boston Celtics            Isaiah Thomas     4.0
12  Boston Celtics              Evan Turner    11.0
13  Boston Celtics              James Young    13.0
14  Boston Celtics             Tyler Zeller    44.0
15   Brooklyn Nets         Bojan Bogdanovic    44.0
16   Brooklyn Nets             Markel Brown    22.0
17   Brooklyn Nets          Wayne Ellington    21.0
18   Brooklyn Nets  Rondae Hollis-Jefferson    24.0
19   Brooklyn Nets             Jarrett Jack     2.0
20   Brooklyn Nets           Sergey Karasev    10.0
21   Brooklyn Nets          Sean Kilpatrick     6.0
22   Brooklyn Nets             Shane Larkin     0.0
23   Brooklyn Nets              Brook Lopez    11.0
24   Brooklyn Nets         Chris McCullough     1.0

In [151]:
select=["Team","Name","Number"]   # LIST MAKING AND CALLING
nba[select]

                       Team                     Name  Number
0            Boston Celtics            Avery Bradley     0.0
1            Boston Celtics              Jae Crowder    99.0
2            Boston Celtics             John Holland    30.0
3            Boston Celtics              R.J. Hunter    28.0
4            Boston Celtics            Jonas Jerebko     8.0
5            Boston Celtics             Amir Johnson    90.0
6            Boston Celtics            Jordan Mickey    55.0
7            Boston Celtics             Kelly Olynyk    41.0
8            Boston Celtics             Terry Rozier    12.0
9            Boston Celtics             Marcus Smart    36.0
10           Boston Celtics          Jared Sullinger     7.0
11           Boston Celtics            Isaiah Thomas     4.0
12           Boston Celtics              Evan Turner    11.0
13           Boston Celtics              James Young    13.0
14           Boston Celtics             Tyler Zeller    44.0
15            Brooklyn Nets         Bojan Bogdanovic    44.0
16            Brooklyn Nets             Markel Brown    22.0
17            Brooklyn Nets          Wayne Ellington    21.0
18            Brooklyn Nets  Rondae Hollis-Jefferson    24.0
19            Brooklyn Nets             Jarrett Jack     2.0
20            Brooklyn Nets           Sergey Karasev    10.0
21            Brooklyn Nets          Sean Kilpatrick     6.0
22            Brooklyn Nets             Shane Larkin     0.0
23            Brooklyn Nets              Brook Lopez    11.0
24            Brooklyn Nets         Chris McCullough     1.0
25            Brooklyn Nets              Willie Reed    33.0
26            Brooklyn Nets          Thomas Robinson    41.0
27            Brooklyn Nets               Henry Sims    14.0
28            Brooklyn Nets             Donald Sloan    15.0
29            Brooklyn Nets           Thaddeus Young    30.0
..                      ...                      ...     ...
428  Portland Trail Blazers          Al-Farouq Aminu     8.0
429  Portland Trail Blazers          Pat Connaughton     5.0
430  Portland Trail Blazers             Allen Crabbe    23.0
431  Portland Trail Blazers                 Ed Davis    17.0
432  Portland Trail Blazers         Maurice Harkless     4.0
433  Portland Trail Blazers         Gerald Henderson     9.0
434  Portland Trail Blazers              Chris Kaman    35.0
435  Portland Trail Blazers           Meyers Leonard    11.0
436  Portland Trail Blazers           Damian Lillard     0.0
437  Portland Trail Blazers            C.J. McCollum     3.0
438  Portland Trail Blazers             Luis Montero    44.0
439  Portland Trail Blazers            Mason Plumlee    24.0
440  Portland Trail Blazers            Brian Roberts     2.0
441  Portland Trail Blazers              Noah Vonleh    21.0
442               Utah Jazz            Trevor Booker    33.0
443               Utah Jazz               Trey Burke     3.0
444               Utah Jazz               Alec Burks    10.0
445               Utah Jazz               Dante Exum    11.0
446               Utah Jazz           Derrick Favors    15.0
447               Utah Jazz              Rudy Gobert    27.0
448               Utah Jazz           Gordon Hayward    20.0
449               Utah Jazz              Rodney Hood     5.0
450               Utah Jazz               Joe Ingles     2.0
451               Utah Jazz            Chris Johnson    23.0
452               Utah Jazz               Trey Lyles    41.0
453               Utah Jazz             Shelvin Mack     8.0
454               Utah Jazz                Raul Neto    25.0
455               Utah Jazz             Tibor Pleiss    21.0
456               Utah Jazz              Jeff Withey    24.0
457                     NaN                      NaN     NaN

[458 rows x 3 columns]

# ADD NEW COLUMN TO THE DATAFRAME

In [152]:
nba["Sport"]= "Cricket"   
# CREATES THE COLUMN AS "=" OPERATORS DOES ,BUT IF WE CARELESSLY MAKE COLUMN EXIST THEN ALL THE VALUES GET OVERIDDED
nba["League"]= "BCCI"
nba.head(46)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Sport,League
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0,Cricket,BCCI
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0,Cricket,BCCI
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN,Cricket,BCCI
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0,Cricket,BCCI
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0,Cricket,BCCI
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0,Cricket,BCCI
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0,Cricket,BCCI
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0,Cricket,BCCI
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0,Cricket,BCCI
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0,Cricket,BCCI
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0,Cricket,BCCI
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,5-9,185.0,Washington,6912869.0,Cricket,BCCI
12,Evan Turner,Boston Celtics,11.0,SG,27.0,6-7,220.0,Ohio State,3425510.0,Cricket,BCCI
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0,Cricket,BCCI
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0,Cricket,BCCI
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,6-8,216.0,NaN,3425510.0,Cricket,BCCI
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,6-3,190.0,Oklahoma State,845059.0,Cricket,BCCI
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0,Cricket,BCCI
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,6-7,220.0,Arizona,1335480.0,Cricket,BCCI
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,6-3,200.0,Georgia Tech,6300000.0,Cricket,BCCI
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,6-7,208.0,NaN,1599840.0,Cricket,BCCI
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0,Cricket,BCCI
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,5-11,175.0,Miami (FL),1500000.0,Cricket,BCCI
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0,Cricket,BCCI
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,6-11,200.0,Syracuse,1140240.0,Cricket,BCCI
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0,Cricket,BCCI
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,6-10,237.0,Kansas,981348.0,Cricket,BCCI
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,6-10,248.0,Georgetown,947276.0,Cricket,BCCI
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,6-3,205.0,Texas A&M,947276.0,Cricket,BCCI
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,6-8,221.0,Georgia Tech,11235955.0,Cricket,BCCI
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0,Cricket,BCCI
31,Lou Amundson,New York Knicks,17.0,PF,33.0,6-9,220.0,UNLV,1635476.0,Cricket,BCCI
32,Thanasis Antetokounmpo,New York Knicks,43.0,SF,23.0,6-7,205.0,NaN,30888.0,Cricket,BCCI
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0,Cricket,BCCI
34,Jose Calderon,New York Knicks,3.0,PG,34.0,6-3,200.0,NaN,7402812.0,Cricket,BCCI
35,Cleanthony Early,New York Knicks,11.0,SF,25.0,6-8,210.0,Wichita State,845059.0,Cricket,BCCI
36,Langston Galloway,New York Knicks,2.0,SG,24.0,6-2,200.0,Saint Joseph's,845059.0,Cricket,BCCI
37,Jerian Grant,New York Knicks,13.0,PG,23.0,6-4,195.0,Notre Dame,1572360.0,Cricket,BCCI
38,Robin Lopez,New York Knicks,8.0,C,28.0,7-0,255.0,Stanford,12650000.0,Cricket,BCCI
39,Kyle O'Quinn,New York Knicks,9.0,PF,26.0,6-10,250.0,Norfolk State,3750000.0,Cricket,BCCI
40,Kristaps Porzingis,New York Knicks,6.0,PF,20.0,7-3,240.0,NaN,4131720.0,Cricket,BCCI
41,Kevin Seraphin,New York Knicks,1.0,C,26.0,6-10,278.0,NaN,2814000.0,Cricket,BCCI
42,Lance Thomas,New York Knicks,42.0,SF,28.0,6-8,235.0,Duke,1636842.0,Cricket,BCCI
43,Sasha Vujacic,New York Knicks,18.0,SG,32.0,6-7,195.0,NaN,947276.0,Cricket,BCCI
44,Derrick Williams,New York Knicks,23.0,PF,25.0,6-8,240.0,Arizona,4000000.0,Cricket,BCCI
45,Tony Wroten,New York Knicks,5.0,SG,23.0,6-6,205.0,Washington,167406.0,Cricket,BCCI

In [153]:
nba.insert(4,column="Reginol country",value="IPL")
nba.head()

,Name,Team,Number,Position,Reginol country,Age,Height,Weight,College,Salary,Sport,League
0,Avery Bradley,Boston Celtics,0.0,PG,IPL,25.0,6-2,180.0,Texas,7730337.0,Cricket,BCCI
1,Jae Crowder,Boston Celtics,99.0,SF,IPL,25.0,6-6,235.0,Marquette,6796117.0,Cricket,BCCI
2,John Holland,Boston Celtics,30.0,SG,IPL,27.0,6-5,205.0,Boston University,NaN,Cricket,BCCI
3,R.J. Hunter,Boston Celtics,28.0,SG,IPL,22.0,6-5,185.0,Georgia State,1148640.0,Cricket,BCCI
4,Jonas Jerebko,Boston Celtics,8.0,PF,IPL,29.0,6-10,231.0,NaN,5000000.0,Cricket,BCCI

# BROADCASTING OPERATIONS

In [154]:
print(nba["Age"].add(5).head(12))  # adds the given column by the value add,sub,aul,div,mod
print(nba["Age"].sub(5).head(12))
print(nba["Age"].mul(5).head(12))
print(nba["Age"].div(5).head(12))
print(nba["Age"].mod(5).head(12))

0     30.0
1     30.0
2     32.0
3     27.0
4     34.0
5     34.0
6     26.0
7     30.0
8     27.0
9     27.0
10    29.0
11    32.0
Name: Age, dtype: float64
0     20.0
1     20.0
2     22.0
3     17.0
4     24.0
5     24.0
6     16.0
7     20.0
8     17.0
9     17.0
10    19.0
11    22.0
Name: Age, dtype: float64
0     125.0
1     125.0
2     135.0
3     110.0
4     145.0
5     145.0
6     105.0
7     125.0
8     110.0
9     110.0
10    120.0
11    135.0
Name: Age, dtype: float64
0     5.0
1     5.0
2     5.4
3     4.4
4     5.8
5     5.8
6     4.2
7     5.0
8     4.4
9     4.4
10    4.8
11    5.4
Name: Age, dtype: float64
0     0.0
1     0.0
2     2.0
3     2.0
4     4.0
5     4.0
6     1.0
7     0.0
8     2.0
9     2.0
10    4.0
11    2.0
Name: Age, dtype: float64

In [155]:
nba=pd.read_csv("nba.csv")
nba["Age"]=nba["Age"].add(5)
nba["Weight in Kilograms"]=nba["Weight"].mul(1000)
nba["Salary in Milions"]=nba["Salary"].div(100000)/10
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Weight in Kilograms,Salary in Milions
0,Avery Bradley,Boston Celtics,0.0,PG,30.0,6-2,180.0,Texas,7730337.0,180000.0,7.730337
1,Jae Crowder,Boston Celtics,99.0,SF,30.0,6-6,235.0,Marquette,6796117.0,235000.0,6.796117
2,John Holland,Boston Celtics,30.0,SG,32.0,6-5,205.0,Boston University,NaN,205000.0,NaN

# value_counts() methods review

In [209]:
nba["Team"].value_counts()    #   like SQL as there may be one (or) players per team
nba["Position"].value_counts().head(15)
nba["Salary"].value_counts()
average=nba["Salary"].div(nba.count())

# DROP COLUM WITH NULL VALUE .dropna()
     drops the particular ROW with NULL values

In [207]:
nba.dropna() 
nba.dropna(axis=0)#deletes the NAN row
nba.dropna(how="all", inplace=True)
nba.tail()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NONE,900000
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NONE,2900000
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NONE,0

In [160]:
nba.dropna(axis=1)   # deletes the NAN column

,Name,Team,Number,Position,Age,Height,Weight,Weight in Kilograms
0,Avery Bradley,Boston Celtics,0.0,PG,30.0,6-2,180.0,180000.0
1,Jae Crowder,Boston Celtics,99.0,SF,30.0,6-6,235.0,235000.0
2,John Holland,Boston Celtics,30.0,SG,32.0,6-5,205.0,205000.0
3,R.J. Hunter,Boston Celtics,28.0,SG,27.0,6-5,185.0,185000.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,34.0,6-10,231.0,231000.0
5,Amir Johnson,Boston Celtics,90.0,PF,34.0,6-9,240.0,240000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,26.0,6-8,235.0,235000.0
7,Kelly Olynyk,Boston Celtics,41.0,C,30.0,7-0,238.0,238000.0
8,Terry Rozier,Boston Celtics,12.0,PG,27.0,6-2,190.0,190000.0
9,Marcus Smart,Boston Celtics,36.0,PG,27.0,6-4,220.0,220000.0
10,Jared Sullinger,Boston Celtics,7.0,C,29.0,6-9,260.0,260000.0
11,Isaiah Thomas,Boston Celtics,4.0,PG,32.0,5-9,185.0,185000.0
12,Evan Turner,Boston Celtics,11.0,SG,32.0,6-7,220.0,220000.0
13,James Young,Boston Celtics,13.0,SG,25.0,6-6,215.0,215000.0
14,Tyler Zeller,Boston Celtics,44.0,C,31.0,7-0,253.0,253000.0
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,32.0,6-8,216.0,216000.0
16,Markel Brown,Brooklyn Nets,22.0,SG,29.0,6-3,190.0,190000.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,33.0,6-4,200.0,200000.0
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,26.0,6-7,220.0,220000.0
19,Jarrett Jack,Brooklyn Nets,2.0,PG,37.0,6-3,200.0,200000.0
20,Sergey Karasev,Brooklyn Nets,10.0,SG,27.0,6-7,208.0,208000.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,31.0,6-4,219.0,219000.0
22,Shane Larkin,Brooklyn Nets,0.0,PG,28.0,5-11,175.0,175000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,33.0,7-0,275.0,275000.0
24,Chris McCullough,Brooklyn Nets,1.0,PF,26.0,6-11,200.0,200000.0
25,Willie Reed,Brooklyn Nets,33.0,PF,31.0,6-10,220.0,220000.0
26,Thomas Robinson,Brooklyn Nets,41.0,PF,30.0,6-10,237.0,237000.0
27,Henry Sims,Brooklyn Nets,14.0,C,31.0,6-10,248.0,248000.0
28,Donald Sloan,Brooklyn Nets,15.0,PG,33.0,6-3,205.0,205000.0
29,Thaddeus Young,Brooklyn Nets,30.0,PF,32.0,6-8,221.0,221000.0
...,...,...,...,...,...,...,...,...
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,25.0,6-8,240.0,240000.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,30.0,6-9,215.0,215000.0
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,28.0,6-5,206.0,206000.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,29.0,6-6,210.0,210000.0
431,Ed Davis,Portland Trail Blazers,17.0,C,32.0,6-10,240.0,240000.0
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,28.0,6-9,215.0,215000.0
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,33.0,6-5,215.0,215000.0
434,Chris Kaman,Portland Trail Blazers,35.0,C,39.0,7-0,265.0,265000.0
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,29.0,7-1,245.0,245000.0
436,Damian Lillard,Portland Trail Blazers,0.0,PG,30.0,6-3,195.0,195000.0
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,29.0,6-4,200.0,200000.0
438,Luis Montero,Portland Trail Blazers,44.0,SG,28.0,6-7,185.0,185000.0
439,Mason Plumlee,Portland Trail Blazers,24.0,C,31.0,6-11,235.0,235000.0
440,Brian Roberts,Portland Trail Blazers,2.0,PG,35.0,6-1,173.0,173000.0
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,25.0,6-9,240.0,240000.0
442,Trevor Booker,Utah Jazz,33.0,PF,33.0,6-8,228.0,228000.0
443,Trey Burke,Utah Jazz,3.0,PG,28.0,6-1,191.0,191000.0
444,Alec Burks,Utah Jazz,10.0,SG,29.0,6-6,214.0,214000.0
445,Dante Exum,Utah Jazz,11.0,PG,25.0,6-6,190.0,190000.0
446,Derrick Favors,Utah Jazz,15.0,PF,29.0,6-10,265.0,265000.0
447,Rudy Gobert,Utah Jazz,27.0,C,28.0,7-1,245.0,245000.0
448,Gordon Hayward,Utah Jazz,20.0,SF,31.0,6-8,226.0,226000.0
449,Rodney Hood,Utah Jazz,5.0,SG,28.0,6-8,206.0,206000.0
450,Joe Ingles,Utah Jazz,2.0,SF,33.0,6-8,226.0,226000.0
451,Chris Johnson,Utah Jazz,23.0,SF,31.0,6-6,206.0,206000.0
452,Trey Lyles,Utah Jazz,41.0,PF,25.0,6-10,234.0,234000.0
453,Shelvin Mack,Utah Jazz,8.0,PG,31.0,6-3,203.0,203000.0
454,Raul Neto,Utah Jazz,25.0,PG,29.0,6-1,179.0,179000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,31.0,7-3,256.0,256000.0
456,Jeff Withey,Utah Jazz,24.0,C,31.0,7-0,231.0,231000.0

In [113]:
nba.dropna(subset=["Salary","College"])  # drops the particular ROW with NULL values
# this deletes the rows who has NAN with salary,Collagee

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Weight in Kilograms,Salary in Milions
0,Avery Bradley,Boston Celtics,0.0,PG,30.0,6-2,180.0,Texas,7730337.0,180000.0,7.730337
1,Jae Crowder,Boston Celtics,99.0,SF,30.0,6-6,235.0,Marquette,6796117.0,235000.0,6.796117
3,R.J. Hunter,Boston Celtics,28.0,SG,27.0,6-5,185.0,Georgia State,1148640.0,185000.0,1.148640
6,Jordan Mickey,Boston Celtics,55.0,PF,26.0,6-8,235.0,LSU,1170960.0,235000.0,1.170960
7,Kelly Olynyk,Boston Celtics,41.0,C,30.0,7-0,238.0,Gonzaga,2165160.0,238000.0,2.165160
8,Terry Rozier,Boston Celtics,12.0,PG,27.0,6-2,190.0,Louisville,1824360.0,190000.0,1.824360
9,Marcus Smart,Boston Celtics,36.0,PG,27.0,6-4,220.0,Oklahoma State,3431040.0,220000.0,3.431040
10,Jared Sullinger,Boston Celtics,7.0,C,29.0,6-9,260.0,Ohio State,2569260.0,260000.0,2.569260
11,Isaiah Thomas,Boston Celtics,4.0,PG,32.0,5-9,185.0,Washington,6912869.0,185000.0,6.912869
12,Evan Turner,Boston Celtics,11.0,SG,32.0,6-7,220.0,Ohio State,3425510.0,220000.0,3.425510
13,James Young,Boston Celtics,13.0,SG,25.0,6-6,215.0,Kentucky,1749840.0,215000.0,1.749840
14,Tyler Zeller,Boston Celtics,44.0,C,31.0,7-0,253.0,North Carolina,2616975.0,253000.0,2.616975
16,Markel Brown,Brooklyn Nets,22.0,SG,29.0,6-3,190.0,Oklahoma State,845059.0,190000.0,0.845059
17,Wayne Ellington,Brooklyn Nets,21.0,SG,33.0,6-4,200.0,North Carolina,1500000.0,200000.0,1.500000
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,26.0,6-7,220.0,Arizona,1335480.0,220000.0,1.335480
19,Jarrett Jack,Brooklyn Nets,2.0,PG,37.0,6-3,200.0,Georgia Tech,6300000.0,200000.0,6.300000
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,31.0,6-4,219.0,Cincinnati,134215.0,219000.0,0.134215
22,Shane Larkin,Brooklyn Nets,0.0,PG,28.0,5-11,175.0,Miami (FL),1500000.0,175000.0,1.500000
23,Brook Lopez,Brooklyn Nets,11.0,C,33.0,7-0,275.0,Stanford,19689000.0,275000.0,19.689000
24,Chris McCullough,Brooklyn Nets,1.0,PF,26.0,6-11,200.0,Syracuse,1140240.0,200000.0,1.140240
25,Willie Reed,Brooklyn Nets,33.0,PF,31.0,6-10,220.0,Saint Louis,947276.0,220000.0,0.947276
26,Thomas Robinson,Brooklyn Nets,41.0,PF,30.0,6-10,237.0,Kansas,981348.0,237000.0,0.981348
27,Henry Sims,Brooklyn Nets,14.0,C,31.0,6-10,248.0,Georgetown,947276.0,248000.0,0.947276
28,Donald Sloan,Brooklyn Nets,15.0,PG,33.0,6-3,205.0,Texas A&M,947276.0,205000.0,0.947276
29,Thaddeus Young,Brooklyn Nets,30.0,PF,32.0,6-8,221.0,Georgia Tech,11235955.0,221000.0,11.235955
30,Arron Afflalo,New York Knicks,4.0,SG,35.0,6-5,210.0,UCLA,8000000.0,210000.0,8.000000
31,Lou Amundson,New York Knicks,17.0,PF,38.0,6-9,220.0,UNLV,1635476.0,220000.0,1.635476
33,Carmelo Anthony,New York Knicks,7.0,SF,37.0,6-8,240.0,Syracuse,22875000.0,240000.0,22.875000
35,Cleanthony Early,New York Knicks,11.0,SF,30.0,6-8,210.0,Wichita State,845059.0,210000.0,0.845059
36,Langston Galloway,New York Knicks,2.0,SG,29.0,6-2,200.0,Saint Joseph's,845059.0,200000.0,0.845059
...,...,...,...,...,...,...,...,...,...,...,...
422,Cameron Payne,Oklahoma City Thunder,22.0,PG,26.0,6-3,185.0,Murray State,2021520.0,185000.0,2.021520
423,Andre Roberson,Oklahoma City Thunder,21.0,SG,29.0,6-7,210.0,Colorado,1210800.0,210000.0,1.210800
424,Kyle Singler,Oklahoma City Thunder,5.0,SF,33.0,6-8,228.0,Duke,4500000.0,228000.0,4.500000
425,Dion Waiters,Oklahoma City Thunder,3.0,SG,29.0,6-4,220.0,Syracuse,5138430.0,220000.0,5.138430
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,32.0,6-3,200.0,UCLA,16744218.0,200000.0,16.744218
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,25.0,6-8,240.0,Kansas,525093.0,240000.0,0.525093
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,30.0,6-9,215.0,Wake Forest,8042895.0,215000.0,8.042895
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,28.0,6-5,206.0,Notre Dame,625093.0,206000.0,0.625093
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,29.0,6-6,210.0,California,947276.0,210000.0,0.947276
431,Ed Davis,Portland Trail Blazers,17.0,C,32.0,6-10,240.0,North Carolina,6980802.0,240000.0,6.980802
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,28.0,6-9,215.0,St. John's,2894059.0,215000.0,2.894059
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,33.0,6-5,215.0,Duke,6000000.0,215000.0,6.000000
434,Chris Kaman,Portland Trail Blazers,35.0,C,39.0,7-0,265.0,Central Michigan,5016000.0,265000.0,5.016000
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,29.0,7-1,245.0,Illinois,3075880.0,245000.0,3.075880
436,Damian Lillard,Portland Trail Blazers,0.0,PG,30.0,6-3,195.0,Weber State,4236287.0,195000.0,4.236287
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,29.0,6-4,200.0,Lehigh,2525160.0,200000.0,2.525160
438,Luis Montero,Portland Trail Blazers,44.0,SG,28.0,6-7,185.0,Westchester CC,525093.0,185000.0,0.525093
439,Mason Plumlee,Portland Trail Blazers,24.0,C,31.0,6-11,235.0,Duke,1415520.0,235000.0,1.415520
440,Brian Roberts,Portland Trail Blazers,2.0,PG,35.0,6-1,173.0,Dayton,2854940.0,173000.0,2.854940
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,25.0,6-9,240.0,Indiana,2637720.0,240000.0,2.637720
442,Trevor Booker,Utah Jazz,33.0,PF,33.0,6-8,228.0,Clemson,4775000.0,228000.0,4.775000
443,Trey Burke,Utah Jazz,3.0,PG,28.0,6-1,191.0,Michigan,2658240.0,191000.0,2.658240
444,Alec Burks,Utah Jazz,10.0,SG,29.0,6-6,214.0,Colorado,9463484.0,214000.0,9.463484
446,Derrick Favors,Utah Jazz,15.0,PF,29.0,6-10,265.0,Georgia Tech,12000000.0,265000.0,12.000000
448,Gordon Hayward,Utah Jazz,20.0,SF,31.0,6-8,226.0,Butler,15409570.0,226000.0,15.409570
449,Rodney Hood,Utah Jazz,5.0,SG,28.0,6-8,206.0,Duke,1348440.0,206000.0,1.348440
451,Chris Johnson,Utah Jazz,23.0,SF,31.0,6-6,206.0,Dayton,981348.0,206000.0,0.981348
452,Trey Lyles,Utah Jazz,41.0,PF,25.0,6-10,234.0,Kentucky,2239800.0,234000.0,2.239800
453,Shelvin Mack,Utah Jazz,8.0,PG,31.0,6-3,203.0,Butler,2433333.0,203000.0,2.433333
456,Jeff Withey,Utah Jazz,24.0,C,31.0,7-0,231.0,Kansas,947276.0,231000.0,0.947276

# FIILING NULL VALUES BY .fillna( )method
      makes NAN VALUES to fill some thing we give

In [223]:
nba=pd.read_csv("nba.csv")
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [224]:
nba.fillna(0).head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,0,5000000.0

In [230]:
nba["Salary"].fillna(0,inplace=True)
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [231]:
nba["College"].fillna("NO college", inplace=True)  # makes NAN VALUES to fill some thing we give 
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NO college,5000000.0

In [232]:
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NO college,5000000.0

# The .astype( )method
helps in changing one form of data of series to change one to  other series

In [296]:
nba=pd.read_csv("nba.csv").dropna(how="all") 
# this rempves the rows with ALL null column values 
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

In [297]:
nba["Salary"].fillna(0,inplace=True)
# this makes all null values in column to "0"
nba["College"].fillna("NONE", inplace=True)
nba.head(6)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NONE,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NONE,12000000.0

In [298]:
nba.dtypes
nba.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 457 entries, 0 to 456
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null float64
Position    457 non-null object
Age         457 non-null float64
Height      457 non-null object
Weight      457 non-null float64
College     457 non-null object
Salary      457 non-null float64
dtypes: float64(4), object(5)
memory usage: 35.7+ KB

In [299]:

nba["Salary"]=nba["Salary"].astype("int")  # converts Salary float to integer
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0

In [300]:
nba["Number"]=nba["Number"].astype("int")      #converts  float to int
nba["Age"]=nba["Age"].astype("int")         #converts  float to int
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0,PG,25,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99,SF,25,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30,SG,27,6-5,205.0,Boston University,0

In [301]:
nba.dtypes
nba.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 457 entries, 0 to 456
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null object
Number      457 non-null int32
Position    457 non-null object
Age         457 non-null int32
Height      457 non-null object
Weight      457 non-null float64
College     457 non-null object
Salary      457 non-null int32
dtypes: float64(1), int32(3), object(5)
memory usage: 30.3+ KB

In [302]:
nba["Age"].astype("float")

0      25.0
1      25.0
2      27.0
3      22.0
4      29.0
5      29.0
6      21.0
7      25.0
8      22.0
9      22.0
10     24.0
11     27.0
12     27.0
13     20.0
14     26.0
15     27.0
16     24.0
17     28.0
18     21.0
19     32.0
20     22.0
21     26.0
22     23.0
23     28.0
24     21.0
25     26.0
26     25.0
27     26.0
28     28.0
29     27.0
       ...
427    20.0
428    25.0
429    23.0
430    24.0
431    27.0
432    23.0
433    28.0
434    34.0
435    24.0
436    25.0
437    24.0
438    23.0
439    26.0
440    30.0
441    20.0
442    28.0
443    23.0
444    24.0
445    20.0
446    24.0
447    23.0
448    26.0
449    23.0
450    28.0
451    26.0
452    20.0
453    26.0
454    24.0
455    26.0
456    26.0
Name: Age, Length: 457, dtype: float64

In [275]:
nba["Position"].nunique()   # this means there are 5 unique values in position column

5

# CATEGORY 
rather than use a string to store a unique string and every single cell it points every cell that has the exact same value to a single object.IE, ALL THE  UNIQUE VALUES ARE CORRESPONDED TOOTHER COLUMNS WITH THEIR RESPECTIVE VALUE.This reduces the size(a->1,2,5,6,7... and b->599,55,44,..) like that

In [303]:
nba["Position"]=nba["Position"].astype("category")

In [304]:
nba["Team"]=nba["Team"].astype("category")

In [306]:
nba.dtypes
nba.info()  
# after converting float -int, categoring the duplicate values we have decreased memory
# meomory is decreased from 35.1kb to 25.8kb

<class 'pandas.core.frame.DataFrame'>
Int64Index: 457 entries, 0 to 456
Data columns (total 9 columns):
Name        457 non-null object
Team        457 non-null category
Number      457 non-null int32
Position    457 non-null category
Age         457 non-null int32
Height      457 non-null object
Weight      457 non-null float64
College     457 non-null object
Salary      457 non-null int32
dtypes: category(2), float64(1), int32(3), object(3)
memory usage: 25.8+ KB

# Sort the Dataframe BY .sort_values() Part-I

In [307]:
nba=pd.read_csv("nba.csv")
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [312]:
nba.sort_values("Name",ascending=False)  
# in data frame the sorting is done according to repective collumn
# where series is 1-D it sorts by.sort_values, 
#but in data frames it gets condused with the column

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
237,Zaza Pachulia,Dallas Mavericks,27.0,C,32.0,6-11,275.0,NaN,5200000.0
271,Zach Randolph,Memphis Grizzlies,50.0,PF,34.0,6-9,260.0,Michigan State,9638555.0
402,Zach LaVine,Minnesota Timberwolves,8.0,PG,21.0,6-5,189.0,UCLA,2148360.0
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
386,Wilson Chandler,Denver Nuggets,21.0,SF,29.0,6-8,225.0,DePaul,10449438.0
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,6-10,220.0,Saint Louis,947276.0
141,Willie Cauley-Stein,Sacramento Kings,0.0,C,22.0,7-0,240.0,Kentucky,3398280.0
385,Will Barton,Denver Nuggets,5.0,SF,25.0,6-6,175.0,Memphis,3533333.0
233,Wesley Matthews,Dallas Mavericks,23.0,SG,29.0,6-5,220.0,Marquette,16407500.0
97,Wesley Johnson,Los Angeles Clippers,33.0,SF,28.0,6-7,215.0,Syracuse,1100602.0
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,6-4,200.0,North Carolina,1500000.0
322,Walter Tavares,Atlanta Hawks,22.0,C,24.0,7-3,260.0,NaN,1000000.0
261,Vince Carter,Memphis Grizzlies,15.0,SG,39.0,6-6,220.0,North Carolina,4088019.0
363,Victor Oladipo,Orlando Magic,5.0,SG,24.0,6-4,210.0,Indiana,5192520.0
343,Udonis Haslem,Miami Heat,40.0,PF,36.0,6-8,235.0,Florida,2854940.0
401,Tyus Jones,Minnesota Timberwolves,1.0,PG,20.0,6-2,195.0,Duke,1282080.0
124,Tyson Chandler,Phoenix Suns,4.0,C,33.0,7-1,240.0,NaN,13000000.0
285,Tyreke Evans,New Orleans Pelicans,1.0,SG,26.0,6-6,220.0,Memphis,10734586.0
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0
345,Tyler Johnson,Miami Heat,8.0,SG,24.0,6-4,186.0,Fresno State,845059.0
327,Tyler Hansbrough,Charlotte Hornets,50.0,PF,30.0,6-9,250.0,North Carolina,947276.0
215,Tyler Ennis,Milwaukee Bucks,11.0,PG,21.0,6-3,194.0,Syracuse,1662360.0
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744.0
325,Troy Daniels,Charlotte Hornets,30.0,SG,24.0,6-4,205.0,Virginia Commonwealth,947276.0
179,Tristan Thompson,Cleveland Cavaliers,13.0,C,25.0,6-9,238.0,Texas,14260870.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
443,Trey Burke,Utah Jazz,3.0,PG,23.0,6-1,191.0,Michigan,2658240.0
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
242,Trevor Ariza,Houston Rockets,1.0,SF,30.0,6-8,215.0,UCLA,8193030.0
45,Tony Wroten,New York Knicks,5.0,SG,23.0,6-6,205.0,Washington,167406.0
...,...,...,...,...,...,...,...,...,...
421,Anthony Morrow,Oklahoma City Thunder,2.0,SG,30.0,6-5,210.0,Georgia Tech,3344000.0
281,Anthony Davis,New Orleans Pelicans,23.0,PF,23.0,6-10,253.0,Kentucky,7070730.0
108,Anthony Brown,Los Angeles Lakers,3.0,SF,23.0,6-7,210.0,Stanford,700000.0
411,Andrew Wiggins,Minnesota Timberwolves,22.0,SG,21.0,6-8,199.0,Kansas,5758680.0
362,Andrew Nicholson,Orlando Magic,44.0,PF,26.0,6-9,250.0,St. Bonaventure,2380593.0
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600.0
78,Andrew Bogut,Golden State Warriors,12.0,C,31.0,7-0,260.0,Utah,13800000.0
423,Andre Roberson,Oklahoma City Thunder,21.0,SG,24.0,6-7,210.0,Colorado,1210800.0
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750.0
83,Andre Iguodala,Golden State Warriors,9.0,SF,32.0,6-6,215.0,Arizona,11710456.0
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0
90,Anderson Varejao,Golden State Warriors,18.0,PF,33.0,6-11,273.0,NaN,289755.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
348,Amar'e Stoudemire,Miami Heat,5.0,PF,33.0,6-10,245.0,NaN,947276.0
287,Alonzo Gee,New Orleans Pelicans,15.0,SF,29.0,6-6,225.0,Alabama,1320000.0
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,6-6,210.0,California,947276.0
275,Alexis Ajinca,New Orleans Pelicans,42.0,C,28.0,7-2,248.0,NaN,4389607.0
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,NaN
128,Alex Len,Phoenix Suns,21.0,C,22.0,7-1,260.0,Maryland,3807120.0
444,Alec Burks,Utah Jazz,10.0,SG,24.0,6-6,214.0,Colorado,9463484.0
135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397.0
368,Alan Anderson,Washington Wizards,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,6-9,215.0,Wake Forest,8042895.0
330,Al Jefferson,Charlotte Hornets,25.0,C,31.0,6-10,289.0,NaN,13500000.0
312,Al Horford,Atlanta Hawks,15.0,C,30.0,6-10,245.0,Florida,12000000.0
404,Adreian Payne,Minnesota Timberwolves,33.0,PF,25.0,6-10,237.0,Michigan State,1938840.0
328,Aaron Harrison,Charlotte Hornets,9.0,SG,21.0,6-6,210.0,Kentucky,525093.0
356,Aaron Gordon,Orlando Magic,0.0,PF,20.0,6-9,220.0,Arizona,4171680.0
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [333]:
nba.sort_values("Age",ascending=False)  
nba.sort_values("Salary",ascending=True)
nba.sort_values("Salary",ascending=False,inplace=True,na_position="last")  
#all the NAN values are at end.
nba.sort_values("Salary",ascending=True,na_position="first") 
nba.sort_values("Salary",ascending=False,na_position="last")

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064.0
349,Dwyane Wade,Miami Heat,3.0,SG,34.0,6-4,220.0,Marquette,20000000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
174,Kevin Love,Cleveland Cavaliers,0.0,PF,27.0,6-10,251.0,UCLA,19689000.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000.0
265,Marc Gasol,Memphis Grizzlies,33.0,C,31.0,7-1,255.0,NaN,19688000.0
96,Blake Griffin,Los Angeles Clippers,32.0,PF,27.0,6-10,251.0,Oklahoma,18907726.0
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659.0
199,Paul George,Indiana Pacers,13.0,SF,26.0,6-9,220.0,Fresno State,17120106.0
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218.0
168,Kyrie Irving,Cleveland Cavaliers,2.0,PG,24.0,6-3,193.0,Duke,16407501.0
418,Enes Kanter,Oklahoma City Thunder,11.0,C,24.0,6-11,245.0,Kentucky,16407500.0
301,Kawhi Leonard,San Antonio Spurs,2.0,SF,24.0,6-7,230.0,San Diego State,16407500.0
233,Wesley Matthews,Dallas Mavericks,23.0,SG,29.0,6-5,220.0,Marquette,16407500.0
220,Greg Monroe,Milwaukee Bucks,15.0,C,26.0,6-11,265.0,Georgetown,16407500.0
153,Jimmy Butler,Chicago Bulls,21.0,SG,26.0,6-7,220.0,Marquette,16407500.0
189,Tobias Harris,Detroit Pistons,34.0,SF,23.0,6-9,235.0,Tennessee,16000000.0
382,John Wall,Washington Wizards,2.0,PG,25.0,6-4,195.0,Kentucky,15851950.0
143,DeMarcus Cousins,Sacramento Kings,15.0,C,25.0,6-11,270.0,Kentucky,15851950.0
249,James Harden,Houston Rockets,13.0,SG,26.0,6-5,220.0,Arizona State,15756438.0
111,Roy Hibbert,Los Angeles Lakers,17.0,C,29.0,7-2,270.0,Georgetown,15592217.0
288,Eric Gordon,New Orleans Pelicans,10.0,SG,27.0,6-4,215.0,Indiana,15514031.0
...,...,...,...,...,...,...,...,...,...
73,Jason Thompson,Toronto Raptors,1.0,PF,29.0,6-11,250.0,Rider,245177.0
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,222888.0
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744.0
123,Chase Budinger,Phoenix Suns,10.0,SF,28.0,6-7,209.0,Arizona,206192.0
303,Kevin Martin,San Antonio Spurs,23.0,SG,33.0,6-7,199.0,Western Carolina,200600.0
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600.0
381,Marcus Thornton,Washington Wizards,15.0,SF,29.0,6-4,205.0,LSU,200600.0
326,Jorge Gutierrez,Charlotte Hornets,12.0,PG,27.0,6-3,189.0,California,189455.0
282,Bryce Dejean-Jones,New Orleans Pelicans,31.0,SG,23.0,6-6,203.0,Iowa State,169883.0
45,Tony Wroten,New York Knicks,5.0,SG,23.0,6-6,205.0,Washington,167406.0
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215.0
184,Lorenzo Brown,Detroit Pistons,17.0,PG,25.0,6-5,189.0,North Carolina State,111444.0
92,Jeff Ayres,Los Angeles Clippers,19.0,PF,29.0,6-9,250.0,Arizona State,111444.0
175,Jordan McRae,Cleveland Cavaliers,12.0,SG,25.0,6-5,179.0,Tennessee,111196.0
135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397.0
130,Phil Pressey,Phoenix Suns,25.0,PG,25.0,5-11,175.0,Missouri,55722.0
291,Orlando Johnson,New Orleans Pelicans,0.0,SG,27.0,6-5,220.0,UC Santa Barbara,55722.0
32,Thanasis Antetokounmpo,New York Knicks,43.0,SF,23.0,6-7,205.0,NaN,30888.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,NaN
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,NaN
264,Jordan Farmar,Memphis Grizzlies,4.0,PG,29.0,6-2,180.0,UCLA,NaN
269,Ray McCallum,Memphis Grizzlies,5.0,PG,24.0,6-3,190.0,Detroit,NaN
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,NaN
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,NaN
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,NaN
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,NaN,NaN
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,NaN
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,NaN
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [334]:
nba.head(15)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000.0
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500.0
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000.0
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364.0
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695.0
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622.0
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064.0
349,Dwyane Wade,Miami Heat,3.0,SG,34.0,6-4,220.0,Marquette,20000000.0
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0
174,Kevin Love,Cleveland Cavaliers,0.0,PF,27.0,6-10,251.0,UCLA,19689000.0
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000.0
265,Marc Gasol,Memphis Grizzlies,33.0,C,31.0,7-1,255.0,NaN,19688000.0
96,Blake Griffin,Los Angeles Clippers,32.0,PF,27.0,6-10,251.0,Oklahoma,18907726.0

# Sort the Dataframe BY .sort_values() Part-II
    (THIS USES LISTS FOR COLUMNS)

In [335]:
nba=pd.read_csv("nba.csv")
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [339]:
nba.sort_values(["Team","Name"],ascending=[True,False]) 
# sorts first team alphabetaccly and in that it does NAme alphabatically
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN

# SORT DATA FRAME WITH THE .sort_index method()
(SORTS DATA FRAME BY THEIR INDEXES)

In [340]:
nba=pd.read_csv("nba.csv")
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [341]:
nba.sort_values(["Number","Salary","Name"],inplace=True)
nba.tail(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
68,Lucas Nogueira,Toronto Raptors,92.0,C,23.0,7-0,220.0,NaN,1842000.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [344]:
nba.sort_index(ascending=False,inplace=True)  #
nba.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0

# RANK VALUES WITH THE .RANK() METHOD
 Generates the brand new series of ranks. This method will execute if there are no NAN values , ie all NAN values should be converted to numbers

In [347]:
nba=pd.read_csv("nba.csv").dropna(how="all")
nba["Salary"]=nba["Salary"].fillna(0).astype("int")
nba.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000

In [358]:
nba["Salary Rank"]=nba["Salary"].rank(ascending=False).astype("int")
nba.head(5)
# gives the rank of salary ie, rank 361 for index 1 like that and HIGH SALLRY GET LOW RANK

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary Rank
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337,97
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117,110
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0,452
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640,322
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000,147

In [364]:
nba.sort_values(by="Salary",ascending=False,inplace=True) # sorting according to salary rank.
nba

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Salary Rank
109,Kobe Bryant,Los Angeles Lakers,24.0,SF,37.0,6-6,212.0,NaN,25000000,1
169,LeBron James,Cleveland Cavaliers,23.0,SF,31.0,6-8,250.0,NaN,22970500,2
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,6-8,240.0,Syracuse,22875000,3
251,Dwight Howard,Houston Rockets,12.0,C,30.0,6-11,265.0,NaN,22359364,4
339,Chris Bosh,Miami Heat,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730,5
100,Chris Paul,Los Angeles Clippers,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695,6
414,Kevin Durant,Oklahoma City Thunder,35.0,SF,27.0,6-9,240.0,Texas,20158622,7
164,Derrick Rose,Chicago Bulls,1.0,PG,27.0,6-3,190.0,Memphis,20093064,8
349,Dwyane Wade,Miami Heat,3.0,SG,34.0,6-4,220.0,Marquette,20000000,9
174,Kevin Love,Cleveland Cavaliers,0.0,PF,27.0,6-10,251.0,UCLA,19689000,11
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,6-11,265.0,Texas A&M,19689000,11
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000,11
294,LaMarcus Aldridge,San Antonio Spurs,12.0,PF,30.0,6-11,240.0,Texas,19689000,11
265,Marc Gasol,Memphis Grizzlies,33.0,C,31.0,7-1,255.0,NaN,19688000,14
96,Blake Griffin,Los Angeles Clippers,32.0,PF,27.0,6-10,251.0,Oklahoma,18907726,15
315,Paul Millsap,Atlanta Hawks,4.0,PF,31.0,6-8,246.0,Louisiana Tech,18671659,16
199,Paul George,Indiana Pacers,13.0,SF,26.0,6-9,220.0,Fresno State,17120106,17
426,Russell Westbrook,Oklahoma City Thunder,0.0,PG,27.0,6-3,200.0,UCLA,16744218,18
168,Kyrie Irving,Cleveland Cavaliers,2.0,PG,24.0,6-3,193.0,Duke,16407501,19
233,Wesley Matthews,Dallas Mavericks,23.0,SG,29.0,6-5,220.0,Marquette,16407500,22
301,Kawhi Leonard,San Antonio Spurs,2.0,SF,24.0,6-7,230.0,San Diego State,16407500,22
418,Enes Kanter,Oklahoma City Thunder,11.0,C,24.0,6-11,245.0,Kentucky,16407500,22
153,Jimmy Butler,Chicago Bulls,21.0,SG,26.0,6-7,220.0,Marquette,16407500,22
220,Greg Monroe,Milwaukee Bucks,15.0,C,26.0,6-11,265.0,Georgetown,16407500,22
189,Tobias Harris,Detroit Pistons,34.0,SF,23.0,6-9,235.0,Tennessee,16000000,25
382,John Wall,Washington Wizards,2.0,PG,25.0,6-4,195.0,Kentucky,15851950,26
143,DeMarcus Cousins,Sacramento Kings,15.0,C,25.0,6-11,270.0,Kentucky,15851950,26
249,James Harden,Houston Rockets,13.0,SG,26.0,6-5,220.0,Arizona State,15756438,28
111,Roy Hibbert,Los Angeles Lakers,17.0,C,29.0,7-2,270.0,Georgetown,15592217,29
288,Eric Gordon,New Orleans Pelicans,10.0,SG,27.0,6-4,215.0,Indiana,15514031,30
...,...,...,...,...,...,...,...,...,...,...
304,Andre Miller,San Antonio Spurs,24.0,PG,40.0,6-3,200.0,Utah,250750,428
73,Jason Thompson,Toronto Raptors,1.0,PF,29.0,6-11,250.0,Rider,245177,429
420,Nazr Mohammed,Oklahoma City Thunder,13.0,C,38.0,6-10,250.0,Kentucky,222888,430
203,Ty Lawson,Indiana Pacers,10.0,PG,28.0,5-11,195.0,North Carolina,211744,431
123,Chase Budinger,Phoenix Suns,10.0,SF,28.0,6-7,209.0,Arizona,206192,432
248,Andrew Goudelock,Houston Rockets,0.0,PG,27.0,6-3,200.0,Charleston,200600,434
381,Marcus Thornton,Washington Wizards,15.0,SF,29.0,6-4,205.0,LSU,200600,434
303,Kevin Martin,San Antonio Spurs,23.0,SG,33.0,6-7,199.0,Western Carolina,200600,434
326,Jorge Gutierrez,Charlotte Hornets,12.0,PG,27.0,6-3,189.0,California,189455,436
282,Bryce Dejean-Jones,New Orleans Pelicans,31.0,SG,23.0,6-6,203.0,Iowa State,169883,437
45,Tony Wroten,New York Knicks,5.0,SG,23.0,6-6,205.0,Washington,167406,438
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,6-4,219.0,Cincinnati,134215,439
92,Jeff Ayres,Los Angeles Clippers,19.0,PF,29.0,6-9,250.0,Arizona State,111444,440
184,Lorenzo Brown,Detroit Pistons,17.0,PG,25.0,6-5,189.0,North Carolina State,111444,440
175,Jordan McRae,Cleveland Cavaliers,12.0,SG,25.0,6-5,179.0,Tennessee,111196,442
135,Alan Williams,Phoenix Suns,15.0,C,23.0,6-8,260.0,UC Santa Barbara,83397,443
130,Phil Pressey,Phoenix Suns,25.0,PG,25.0,5-11,175.0,Missouri,55722,444
291,Orlando Johnson,New Orleans Pelicans,0.0,SG,27.0,6-5,220.0,UC Santa Barbara,55722,444
32,Thanasis Antetokounmpo,New York Knicks,43.0,SF,23.0,6-7,205.0,NaN,30888,446
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,0,452
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,6-9,254.0,Duke,0,452
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,0,452
171,Dahntay Jones,Cleveland Cavaliers,30.0,SG,35.0,6-6,225.0,Duke,0,452
397,Axel Toupane,Denver Nuggets,6.0,SG,23.0,6-7,210.0,NaN,0,452
269,Ray McCallum,Memphis Grizzlies,5.0,PG,24.0,6-3,190.0,Detroit,0,452
353,Dorell Wright,Miami Heat,11.0,SF,30.0,6-9,205.0,NaN,0,452
264,Jordan Farmar,Memphis Grizzlies,4.0,PG,29.0,6-2,180.0,UCLA,0,452
409,Greg Smith,Minnesota Timberwolves,4.0,PF,25.0,6-10,250.0,Fresno State,0,452
273,Alex Stepheson,Memphis Grizzlies,35.0,PF,28.0,6-10,270.0,USC,0,452
270,Xavier Munford,Memphis Grizzlies,14.0,PG,24.0,6-3,180.0,Rhode Island,0,452